# ik heb eerst geprobeerd deze guide van kubernetes zelf te gebruiken, maar deze lukte niet: https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# https://buildvirtual.net/deploy-a-kubernetes-cluster-using-ansible/
# - name: Configure node ip
#   lineinfile:
#     path: /etc/default/kubelet
#     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
#     - name: Restart kubelet
#       service:
#         name: kubelet
#         daemon_reload: yes
#         state: restarted
#     # initialise
#     - name: cleanup - stop the kubelet service
#       command: systemctl stop kubelet.service
#     - name: cleanup - reset the kubelet service
#       command: kubeadm reset
# # vagrant user toegang geven tot cluster
# - name: Setup kubeconfig for vagrant user
#   command: "{{ item }}"
#   with_items:
#     - mkdir -p $HOME/.kube
#     - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#     - sudo chown $(id -u):$(id -g) $HOME/.kube/config
# # Setup container met networking provider & network policy engine
# - name: Install calico pod network
#   become: false
#   command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

---
- hosts: all
  become: true
  tasks:
    - name: basisinstallatie k8s
      include: k8sinstallation.yml

    # k8s cluster initialiseren en opstarten
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10"

    # commando die een join-command file gaat genereren met info die nodes gebruiken om cluster te joinen
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
# # checken of docker runned
#       # handlers:
#       #   - name: docker status
#       #     service: name=docker state=started
