- hosts: all
  become: true
  tasks:
    - name: basisinstallatie k8s
      include: k8sinstallation.yml
      
    # k8s cluster initialiseren en opstarten
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10" 
      # commando die een join-command file gaat genereren met info die nodes gebruiken om cluster te joinen
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    # vagrant user toegang geven tot cluster
    - name: Setup kubeconfig for vagrant user
      command: mkdir -p $HOME/.kube
    - name: Setup kubeconfig for vagrant user
      command: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - name: Setup kubeconfig for vagrant user
      command: sudo chown $(id -u):$(id -g) $HOME/.kube/config
      

      
    
        