---
- hosts: all
  become: true
  tasks:
    - name: basisinstallatie k8s
      include: k8sinstallation.yml

    # - name: Configure node ip
    #   lineinfile:
    #     path: /etc/default/kubelet
    #     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

# cluster van master node joinen
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

# checken of docker runned
  handlers:
    - name: docker status
      service: name=docker state=started