---
- hosts: all
  become: true
  tasks:
    - name: Installeer packages zodat apt over https kan gebruikt worden
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Voeg apt signing key toe aan Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Voeg apt repository toe voor stable version
      apt_repository:
        url: https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Installeer docker met dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        notify:
          - docker status

    - name: Voeg vagrant user aan docker group toe
      user:
        name: vagrant
        group: docker

# swap disablen (kwni goe waarom, tutorial zegt zo)
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

# kubernetes componenten installeren
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl

    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

# cluster van master node joinen
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
  
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh