# ik heb eerst geprobeerd deze guide van kubernetes zelf te gebruiken, maar deze lukte niet: https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# https://buildvirtual.net/deploy-a-kubernetes-cluster-using-ansible/
